### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#56]
Write docs and implement WindNODE's corporate design

**Comment by gplssm** [comment]
With sphinx-material, you can specify ` theme_color `, ` color_primary `, `color_accent` , [see here](https://bashtage.github.io/sphinx-material/customization.html). But, you can only choose from a list of pre-defined colors. In order to use custom colors, we need to the option `html_css_files` as described [here](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html).

The task "write documentation" is too broad. I would like to re-focus this issue towards only implement the corporate design. I would like to create several separate issues. One for each section of the documentation. Ok?

**Comment by nesnoj** [comment]
yepp, go for it

**Comment by nesnoj** [comment]
Done in other issues, closing...
